name: Update latest_shorts.json

on:
  schedule:
    - cron: "10 8 * * 1-5"   # 17:10 JST on weekdays
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml pandas xlrd pykakasi

      - name: Run updater
        run: |
          python -m scripts.update_latest_short

      - name: Commit & Push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain latest_shorts.json)" ]]; then
            git add latest_shorts.json
            git commit -m "chore(data): update latest_shorts.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
